<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Do You Want to Go Out With Me?</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }
        .container {
            margin-top: 100px;
        }
        button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }
        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Do You Want to Go Out With Me?</h1>
        <button onclick="askOut()">Click to find out!</button>
    </div>
    <script>
        function askOut() {
            var answer = confirm("Would you like to go out with me?");
            if (answer) {
                alert("Great! Let's plan something :)");
            } else {
                alert("No worries, maybe another time!");
            }
        }
    </script>
</body>
</html>
